name: CI Manual Regression

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-manual-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-sdk:
    name: build-sdk (${{ matrix.platform }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-arm64
            runner: windows-arm64
          # - platform: linux-arm64
          #   runner: ubuntu-latest
          # - platform: android-arm64
          #   runner: ubuntu-latest
    uses: ./.github/workflows/_build-sdk.yml
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      runner: ${{ matrix.runner }}
      upload_artifact: true

  build-cli:
    name: build-cli (${{ matrix.platform }})
    needs: [build-sdk]
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-arm64
            runner: windows-arm64
    uses: ./.github/workflows/_build-cli.yml
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
      runner: ${{ matrix.runner }}
